### ISSUE TITLE
Looking to help

### ISSUE THREAD

**Issue by Kreuger** [plips-nl/BlUVO#1]
Hey I'd like to help with this project as Im learning Python. I noticed that youre using DarkSky for the weather. It should be noted that this app is being discontinued on Android. Also it looks like you have the code ready for the EU market. Are you planning to implement a way to detect the region and pull the info from a file or have separate settings for each one within the main app? And Im wondering if there's anything specific that needs to be done?

**Comment by plips-nl** [comment]
Darksky api is discontinued by the end of 2021. Gives me a while to workaround it. Maybe switch to OpenWeatherMap api. I am not planning to extend it beyond europe. API and Logon procedures are very different. You might wanna check uit BlueLinky, which is in TS but had the API for Canada and US.

**Comment by Kreuger** [comment]
Yeah that was how I found your project but because I wanted to learn python anyways, it seemed like a good place to jump in.

**Comment by plips-nl** [comment]
I'll be updating the lib tonight. Made a working integration with domoticz. 
Still to be tested is a integration with the OpenWeatherAPI (you now can enter several weather providers)
Work to be done is: error handling in Domoticz, making the script more objectoriented.
So feel free to hop-in!
